### ISSUE TITLE
RFC: Container Image Tagging Convention

### ISSUE THREAD

**Issue by erkannt** [libero/community#36]
## Definition of Done:

- [ ] adr with _proposed_ state is merged and can be applied to Libero Reviewer for evaluation

## Related

Originating discovery issue [elife/5482](https://github.com/elifesciences/issues/issues/5482)

## Tasks

- [ ] define tag lifecycle from component to umbrella and from dev to release
- [ ] define tag naming and versioning convention
- [ ] check for obvious implementation roadblocks when using GithubAction, Dependabot/Renovate/Flux
- [ ] collect feedback from product teams
